name: CI Pipeline

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install black isort pylint pytest pytest-cov mypy

      - name: Configure environment
        run: |
          export PYTHONPYCACHEPREFIX=$PWD/pycache
          mkdir -p $PWD/pycache
          export PYTEST_CACHE_DIR=$PWD/.pytest_cache
          mkdir -p $PWD/.pytest_cache

      - name: Set PYTHONPATH
        run: |
          export PYTHONPATH=$(find $PWD -type d -name 'p_[0-9]*_*' | tr '\n' ':'):$PWD:$PWD/p_1_two_sum/src
          echo "PYTHONPATH=$PYTHONPATH"

      - name: Run pytest
        run: |
          source venv/bin/activate
          for project_dir in $(find $PWD -maxdepth 1 -type d -name 'p_[0-9]*_*'); do
            if [ -d "$project_dir/tests" ]; then
              echo "Running tests for $(basename $project_dir)..."
              pytest "$project_dir/tests/" -v --cov="$project_dir/src"
            fi
          done

      - name: Run pylint
        run: |
          source venv/bin/activate
          for project_dir in $(find $PWD -maxdepth 1 -type d -name 'p_[0-9]*_*'); do
            if [ -d "$project_dir/src" ]; then
              echo "Running pylint for $(basename $project_dir)..."
              pylint --disable=C,R,W --fail-under=8.0 "$project_dir/src"/*.py "$project_dir/tests"/*.py
            fi
          done

  push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64
